# Generated by Django 5.1.2 on 2024-10-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='chead0',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='chead2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head0',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='head2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
