# Generated by Django 5.1.2 on 2024-11-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_blogpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogpost',
            new_name='Blog',
        ),
    ]
